name: Submit Dependency Graph
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions: write-all

jobs:
  generate-and-submit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - name: Setup Gradle
      uses: gradle/actions/dependency-submission@v3
      env:
        DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}
